### ISSUE TITLE
Not working with emacs24?

### ISSUE THREAD

**Issue by intuser** [vspinu/zotelo#19]
I just tried out zotelo with emacs24 and iceweasel 31.5.0

If I do a "zotelo-set-collection" or "zotelo-update-database" I always get an error:
```
Debugger entered--Lisp error: (error "MozError: 
\":MozOk:\"
repl> ")
 signal(error ("MozError: \n\":MozOk:\"\nrepl> "))
  error("MozError: \n%s" "\":MozOk:\"\nrepl> ")
  zotelo-update-database()
  call-interactively(zotelo-update-database record nil)
  command-execute(zotelo-update-database record)
  execute-extended-command(nil "zotelo-update-database")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```
I followed your troubleshooting guide and used zotelo-verbose to get the javascript and executed it in a telnet connection to moz-repl - this works well and the updated collection is created.

\*moz-command-output\* is:
```
":MozOk:"
repl> 
```
\*zoteloMozRepl\*
```
 - If you get stuck at the "...>" prompt, enter a semicolon (;) at the beginning of the line to force evaluation.
 - If you get errors after every character you type, see http://github.com/bard/mozrepl/wikis/troubleshooting (short version: stop using Microsoft telnet, use netcat or putty instead)

Current working context: chrome://browser/content/browser.xul
Current input mode: syntax

repl> 
```

**Comment by vspinu** [comment]
> Debugger entered--Lisp error: (error "MozError: 
\":MozOk:\"

You have`case-fold-search` set to nil right?  There was a typo (MozOk instead of MozOK) which was not detected with the default `case-fold-search`. Thanks!

**Comment by intuser** [comment]
Yes, I have `case-fold-search` set to nil. And the change form MozOk to MozOK solves the problem Thanks!
