### ISSUE TITLE
Fields with %-signs break creation of aux files

### ISSUE THREAD

**Issue by arejensen** [vspinu/zotelo#20]
I spent a couple of hours debugging a rather large bib file tonight. I kept getting weird errors about not being able to include certain references.
After a while I discovered that if url fields in Zotero contain %-signs, any reference *below* the offending entry will break with weird error messages. This is especially surprising when a compiles fine, but when adding a reference in the middle of the document, suddenly several others break without any clear indication as to why.

I'll try to reproduce the bug in other ways as well in case I've misunderstood the problem.

If you believe this is a bug worth fixing, I can probably submit a patch within the end of next week.

**Comment by vspinu** [comment]
> If you believe this is a bug worth fixing, 

I am not sure I understand the nature of the problem. Even if this is indeed a bug, it's a bug with zotero not zotelo. Zotelo just asks Zotero to export the collection. Moreover, url's commonly contain % sign. So it's rather improbably that bibtex/biblatex don't handle those correctly. Something weird is going on.

**Comment by arejensen** [comment]
I made an MWE and was able to reproduce the error when using plainnat as the bibliography style. I could not, however, reproduce the error when using the apalike bibliography style. Reading through their source code--albeit very quickly--I found that the first use urls in the bibliography output, whereas the second does not. Note that the problem only occurs when bibtex tries to pull in a reference with an offending url field, and the bibliography style includes urls. I would venture a guess that the bug appears when the offending field is read into the document. Since it cointains an unescaped %, the field is never closed with a }, thus malformating the document.

After reading through the zotelo code, it seems it relies on zotero's internals to export the bibtex code. Is that correct? If that's the case, I'll open a bug in the zotero project instead.

(Regardless, anyone that might be reading this, be aware that by stripping any url field containing an unescaped % will fix this issue. Or use a bibliography style that won't reference any url fields.)

Below is an offending bib-file entry:

```latex
@article{pelletier_associations_2001,
	title = {Associations {Among} {Perceived} {Autonomy} {Support}, {Forms} of {Self}-{Regulation}, and {Persistence}: {A} {Prospective} {Study}},
	volume = {25},
	issn = {0146-7239, 1573-6644},
	shorttitle = {Associations {Among} {Perceived} {Autonomy} {Support}, {Forms} of {Self}-{Regulation}, and {Persistence}},
	url = {http://link.springer.com/article/10.1023/A%3A1014805132406},
	doi = {10.1023/A:1014805132406},
	abstract = {snipped},
	language = {en},
	number = {4},
	urldate = {2015-04-28},
	journal = {Motivation and Emotion},
	author = {Pelletier, Luc G. and Fortier, Michelle S. and Vallerand, Robert J. and Bri{\`e}re, Nathalie M.},
	month = dec,
	year = {2001},
	keywords = {autonomy support, Clinical Psychology, Developmental Psychology, persistence, Psychology of Personality, self-determination theory, self-regulation, Social Psychology},
	pages = {279--306}
}
```

**Comment by vspinu** [comment]
> After reading through the zotelo code, it seems it relies on zotero's internals to export the bibtex code. Is that correct? If that's the case, I'll open a bug in the zotero project instead.

Have you missed my comment above? It's not a zotelo bug but rather the one with zotero. You should be able to reproduce it with plan zotero export.

**Comment by arejensen** [comment]
| Zotelo just asks Zotero to export the collection. 

I read that wrong, I'm sorry.
I'll investigate whether this is a known bug in zotero, and possibly submit a patch.
