### ISSUE TITLE
Recent changes break compatibility with Zotero standalone

### ISSUE THREAD

**Issue by moble** [vspinu/zotelo#21]
I've been happily using this code for a while with Zotero standalone.  But after updating to the most recent release, I'm having problems.  I can still use it with Zotero in Firefox with no problem.  But if I'm just running standalone, nothing in `zotelo` works.  For example, if I try to set the collection, it shows me the correct list of collections in my Zotero library, but once I select one, it gives me an error saying `No charsets found or error occured see *moz-command-output* buffer for clues.`  Everything is up-to-date.

It seems to be a problem with the `CharsetMenu` variable not being defined.  Rolling back to 0e3fccd46757f3bfc4c6eb830e65ad34c6e3431a, the commit just before merging the charset stuff from @mliertzer (and without changing anything about my Zotero standalone setup, or even restarting it), makes things work again.

I don't mind poking around a little, but I have no idea where `CharsetMenu` is supposed to be defined, or why it wouldn't be in Zotero standalone.  Any help would be appreciated.  Thanks.

---

This is the output when I make `zotelo-verbose`:

```
zotelo verbose 't'
Auto-saving...

 zotelo message [Wed May 27 14:44:26 2015]
 Moz-command finished

 zotelo message [Wed May 27 14:44:26 2015]
 Moz-command finished

 zotelo message [Wed May 27 14:44:26 2015]
 Collections:
 71 /Books
103 /Books/Math
78 /Books/Mine
81 /Books/Mine/Other
80 /Books/Mine/Physics
79 /Books/Not Mine
61 /Math
139 /Math/General
62 /Math/Geometric Algebra
100 /Math/Geometric Algebra/Algebra
123 /Math/Geometric Algebra/Complex Analysis
124 /Math/Geometric Algebra/Complex Analysis/Geometry of the Cauchy-Riemann Eqs.
101 /Math/Geometric Algebra/Computing
135 /Math/Geometric Algebra/Efficient multiplication
95 /Math/Geometric Algebra/GR
97 /Math/Geometric Algebra/Guide to GA in Practice
126 /Ma

 zotelo message [Wed May 27 14:44:27 2015]
 Moz-command finished

 zotelo message [Wed May 27 14:44:27 2015]
 Moz-command finished

 zotelo message [Wed May 27 14:44:27 2015]
 Translators:
 'TEI' 032ae9b7-ab90-9205-a479-baf81f49184a 'xml'
'Zotero RDF' 14763d24-8ba0-45df-8f52-b8d1108e7ac9 'rdf'
'Better BibLaTeX' f895aa0d-f28e-47fe-b247-2ea77c6ed583 'bib'
'Bibliontology RDF' 14763d25-8ba0-45df-8f52-b8d1108e7ac9 'rdf'
'MODS' 0e2235e7-babf-413c-9acf-f27cce5f059c 'xml'
'Simple Evernote Export' 18dd188a-9afc-4cd6-8775-1980c3ce0fbf 'enex'
'BibLaTeX' b6e39b57-8942-4d11-8259-342c46ce395f 'bib'
'Bookmarks' 4e7119e0-02be-4848-86ef-79a64185aad8 'html'
'CSL JSON' bc03b4fe-436d-4a1f-ba59-de4d2d

 zotelo message [Wed May 27 14:44:27 2015]
 Moz-command finished

 zotelo message [Wed May 27 14:44:27 2015]
 Charsets:
 !!! ReferenceError: CharsetMenu is not defined

Details:


repl> 
zotelo--get-charsets: No charsets found or error occured see *moz-command-output* buffer for clues.
```

The `zoteloMozRepl` buffer is just

```

Welcome to MozRepl.

 - If you get stuck at the "...>" prompt, enter a semicolon (;) at the beginning of the line to force evaluation.
 - If you get errors after every character you type, see http://github.com/bard/mozrepl/wikis/troubleshooting (short version: stop using Microsoft telnet, use netcat or putty instead)

Current working context: chrome://zotero/content/standalone/standalone.xul
Current input mode: syntax

repl> 
```

The Zotero standalone debug log has lots of database queries, and ends like this

```
(5)(+0000001): SELECT collectionID AS id, collectionName AS name FROM collections C WHERE parentCollectionID =47

(5)(+0000000): No child collections of collection 47

(5)(+0000000): SELECT collectionID AS id, collectionName AS name FROM collections C WHERE parentCollectionID =67

(5)(+0000000): No child collections of collection 67

(5)(+0000000): SELECT groupID FROM groups ORDER BY name COLLATE locale

(3)(+0000811): Translate: WARNING: new Zotero.Translate() is deprecated; please don't use this if you don't have to

(3)(+0000001): Translate: All translator detect calls and RPC calls complete
```

**Comment by vspinu** [comment]
Sorry to hear that. I didn't even know that zotelo works with standalone. What is your setup? Can we place some instructions into readme?

>  zotelo--get-charsets: No charsets found or error occured see *moz-command-output* buffer for clues.

If we cannot fix that, we can simply fall back on the old ways. @mliertzer any ideas?

> (3)(+0000811): Translate: WARNING: new Zotero.Translate() 

This one is also worrisome. I would really appreciate if someone can have a look. I am a bit out of academia at the moment and don't write papers anymore.

**Comment by moble** [comment]
Yeah, it's generally worked great with standalone.  For me, at least, Firefox got way too slow to be my browser, and having it open just for zotero is a real pain.  So I've just switched to using the standalone.  I didn't want to bother forking the project just to edit the README, so I've just added the standalone installation instructions to [this wiki page](https://github.com/vspinu/zotelo/wiki/Standalone).  Of course, I'm happy to see you use that however you wish.

**Comment by vspinu** [comment]
Thanks! I will probably move it into readme. There is no much point in spreading docs across multiple sources for such a small project.

**Comment by mliertzer** [comment]
I just had a quick look at it and I believe my pull request should fix the problem. I don't have zotero standalone installed, so @moble could you test the pull request? Thx

**Comment by moble** [comment]
Oh, I meant to say that here.  Yes, this fixes it.  Thank you very much.
