### ISSUE TITLE
Setting zotero-collection in elisp

### ISSUE THREAD

**Issue by psamim** [vspinu/zotelo#31]
By default when setting the Zotero collection, it is saved in a file local variable, like this:

```org
# Local Variables:
# zotero-collection: #("10" 0 2 (name "redhat"))
# End:
```
How can I set `zotero-collection` in elisp? I tried the code below with no luck.

```elisp
(setq 
 zotero-collection (propertize "10" 'name "redhat"))
```
Thanks

**Comment by vspinu** [comment]
Thanks for this. The value was taken directly from the file local variables alist. I have changed it to pick it up from local value of zotero-colleciton. No need to propertize the id, it's just for information purpose. So something like 

``` elisp
(setq-local zotero-collection "10") 
(zotelo-update-database)
```

should work.

You can also call `zoterlo-update-database` with an explicit `ID` argument.

**Comment by psamim** [comment]
Thanks for the update. :)
